### ISSUE TITLE
Failing to compile after applying plugin

### ISSUE THREAD

**Issue by peppercat10** [deepmedia/Grease#1]
Hi. I'm trying to use Grease on a default KMM project. Once I apply the plugin and sync, I get the following error:

`Caused by: java.lang.NoSuchMethodError: 'org.gradle.api.file.FileCollection com.android.build.gradle.internal.tasks.MergeFileTask.getInputFiles()'`

Do you have any idea what might be happening?
Thanks

**Comment by peppercat10** [comment]
Gradle version: 7.0.2
Stacktrace: https://gist.github.com/peppercat10/795488d9663082c81f8d8a325e4fd0b6

Thanks for looking into this!

**Comment by DastanIqbal** [comment]
Facing same issue 
`Caused by: java.lang.NoSuchMethodError: 'org.gradle.api.file.FileCollection com.android.build.gradle.internal.tasks.MergeFileTask.getInputFiles()'
	at io.deepmedia.tools.grease`

**Comment by natario1** [comment]
Should be fixed in latest version.
