### ISSUE TITLE
Embedded classes accessibility control

### ISSUE THREAD

**Issue by TECTRO-SRAVNIRU** [deepmedia/Grease#21]
Is it possible to control the accessibility of classes within an aar assembly pipeline? 

For example, replace the public access modifiers of classes or methods from embedded modules with internal to restrict access to them from the outside of library?

**Comment by 0xera** [comment]
This is not within the scope of this plugin. You can achieve your goals using AGP feature https://developer.android.com/reference/tools/gradle-api/8.3/null/com/android/build/api/variant/Instrumentation#transformClassesWith(java.lang.Class,com.android.build.api.instrumentation.InstrumentationScope,kotlin.Function1)
