### ISSUE TITLE
Support local project dependencies

### ISSUE THREAD

**Issue by natario1** [deepmedia/Grease#4]
grease(project(":other-project")) doesn't work: https://github.com/deepmedia/Grease/blob/v0.3.0/tests/sample-library/build.gradle.kts#L71-L73

**Comment by 0xera** [comment]
It looks strange because main purpose of agp 8 support was  to fix local projects merging :) I have tested it now and it works for me...

**Comment by natario1** [comment]
It failed for me today on that line, using cd tests && ../gradlew sample-library:assembleDebug. Something like that.

I guess AGP properly configures `api` and `implementation` configurations to fallback on release buildType, but we may have to do the same on `grease` configurations.
