### ISSUE TITLE
It doesn't work with @Composable

### ISSUE THREAD

**Issue by HBaadr** [deepmedia/Grease#6]
It give Unresolved reference for composable created in my library

**Comment by 0xera** [comment]
HI. Could you share more details or maybe you have a sample project to reproduce problem?

**Comment by HBaadr** [comment]
Hi, I've integrated Grease into my project and used it to generate an AAR for a library that includes both a Jetpack Compose view and its corresponding ViewModel. While I'm able to include the ViewModel from the AAR in my main Android application, I'm having trouble including the Compose view. The view doesn't seem to be recognized or accessible in the application. Is there a specific configuration or step I might be missing to properly bundle and reference Compose views using Grease?

**Comment by 0xera** [comment]
It seems we forgot to include some kotlin metadata about top level functions. I will try to fix it as soon as possiblle

**Comment by HBaadr** [comment]
Thanks Boss
